### ISSUE TITLE
Retain tags during conversion

### ISSUE THREAD

**Issue by chhh** [DannyBen/FlicFlac#1]
Great tool, thanks!
It would be very useful if it could retain at least artist and title tags when converting e.g. from FLAC to MP3.
I guess that's because FLAC to MP3 is a two step conversion. But as you're already creating a temp file for the intermediate you might as well create an extra text temp file with song title and artist name to copy over to MP3.

**Comment by DannyBen** [comment]
Meta data was never a priority for me, and since each format has its own tagging scheme, adding such a functionality will complicate things, and I am not even sure it is doable with all the "nested" conversions FlicFlac handles.

If you have any information to the contrary, please share.
