### ISSUE TITLE
32-bit float .WAV?

### ISSUE THREAD

**Issue by Sonnenfleck** [DannyBen/FlicFlac#10]
When I tried to convert a Zoom F3 recording, which is in 32-bit float WAV format, I just get an error message - "Failed to convert". Are 32-bit float WAV files not supported by FlicFlac in general or is it just a problem with the decoders Windows uses by default? Is it possible to add support for 32-bit float WAV files?

**Comment by DannyBen** [comment]
It could be a matter of upgrading the one of the bundled encoders.

- Can you provide a small sample file?
- Which format did you want to convert to?

**Comment by Sonnenfleck** [comment]
I tried to convert to mp3 and used the first of these sample files:
[Dropbox – Zoom F3 recordings – Simplify your life](https://www.dropbox.com/sh/1yvihd8d3w85utv/AABi1Xt45XYR-0wj3YsqlmuHa?dl=0)

Of the encoders supplied with FlicFlac, only the ogg encoder seems to be able to handle 32-bit float WAV files. But you set me on the right path: Using Fileblender instead of FlicFlac and lame3.100-64 instead of the supplied version, I could convert the files. Is it possible to use lame 3.100 for FlicFlac? If not, I'm happy to use Fileblender.

**Comment by DannyBen** [comment]
Yes, I can confirm that a newer lame works.
I could not find a standalone flac.exe to deal with the flac conversion.

I can release a new FlicFlac with an updated lame.exe - did you find an official download page? I only found a compiled binary on [RareWares](https://www.rarewares.org/mp3-lame-bundle.php)

**Comment by Sonnenfleck** [comment]
I got the binaries from somewhere else, but RareWares is the only page with Windows binary listed on the lame SourceForge site: https://lame.sourceforge.io/links.php#Binaries - so I guess it's semi-official?

The lastest FLAC release on RareWares (1.4.2) indeed doesn't seem to work.

**Comment by DannyBen** [comment]
Ok - I will release one.
Just know that after getting the new version, you will have to delete the lame.exe from your Windows user's temp directory, so FlicFlac can put the new version there again.

**Comment by Sonnenfleck** [comment]
Thanks alot!

**Comment by DannyBen** [comment]
Ok. Its done, binary release is here:
https://sector-seven.com/software/flicflac

Just delete the lame.exe from the user's temp ( open `%LOCALAPPDATA%\temp` in file explorer and find lame.exe )

If you can confirm, we can close this ticket.

**Comment by Sonnenfleck** [comment]
Can confirm it works - thanks!
