### ISSUE TITLE
Issue with FLAC to MP3 conversion

### ISSUE THREAD

**Issue by smcclosr** [DannyBen/FlicFlac#11]
when doing a bulk conversion from FLAC TO MP3, the tags of Artist, Album, Track, an Genre do not carry over, they are blank

Also the tag for year will enter current year, not the one that is in the file.

**Comment by smcclosr** [comment]
I did  a little research, and noticed that you are going from FLAC -> WAV -> MP3 and using lame for the encoding, and of course unless you save the extracted tag data, then it will be lost.  It looks like ffmpeg is a better tool because you can go straight from FLAC to MP3 and all tag data is preserved.  

Using this command on the command line will do a conversion in the directory:

for %A in (*.flac) do ffmpeg  -i "%~nA.flac"  -c:v copy  -b:a 320k  "%~nA.mp3"

I didn't develop it but found it here: https://superuser.com/questions/1349737/converting-flac-to-mp3-using-ffmpeg

Guessing that your app invokes lame.exe so if you are inclined this would give you a pathway to replace lame with ffmpeg.

**Comment by DannyBen** [comment]
This was discussed in #1.
It is not FlicFlac's objective to retain meta tags, and ffmpeg is an overkill, in terms of bloat and size, for these simple audio tasks.  It is unlikely to find its way into FlicFlac.

**Comment by smcclosr** [comment]
I can see your point if you had to develop a way to extract and preserve the tags, that would take a lot of work, but I have to disagree that ffmpeg is bloat, because there would only be an exchange of lame.exe for ffmpeg.exe, a file for file.

Thank you for the quick response.

**Comment by DannyBen** [comment]
See the size of ffmpeg.exe and the size of lame.exe.
