### ISSUE TITLE
MP3 - Custom setting - how to change?

### ISSUE THREAD

**Issue by imrecsoka** [DannyBen/FlicFlac#12]
Hi, when i select a preset for MP3 output mode. I want to select Custom, but i dont see how to  tweak the settings for Custom?

**Comment by DannyBen** [comment]
Hi. Click the "Open INI File" - it will open FlicFlac.ini, and in it you will find the `[MP3]` section, with some settings.
When you are encoding with the Custom settings, it will use the settings from this section.

```ini
;-------------------------------------------------------------------------------
[MP3]
;-------------------------------------------------------------------------------
; May be CBR or VBR
; Default: CBR
Mode=CBR

; KBPS for CBR encoding
; Default: 192
CBRKbps=192

; May be 0-9 - 0=high quality, bigger files. 9=smaller files
; Default: 4
VBRLevel=4

; Set the minimum-maximum bitrate for VBR.
; Default: 32-320
VBRRate=32-320
```

You can also update any other setting here, including adding your own presets.
