### ISSUE TITLE
Flac to Mp3 - Copy Metadata?

### ISSUE THREAD

**Issue by bravoland** [DannyBen/FlicFlac#13]
Hello. Is there anyway to have FlicFlac copy the metadata to the MP3? currently all this info gets lost and it simply writes the file name to the title field.
![image](https://user-images.githubusercontent.com/35783858/213614951-29a20f74-d481-4cae-9d4b-337c9ca746f0.png)

**Comment by DannyBen** [comment]
Metdata is not preserved, sorry.
Was discussed in #6.

**Comment by bravoland** [comment]
Thanks for the quick reply

Very nice program!
