### ISSUE TITLE
VirusTotal: 4 malware detection in FlicFlac.exe

### ISSUE THREAD

**Issue by Luc4Piccinini** [DannyBen/FlicFlac#15]
Problem: 4 Malware detected.

Bkavpro:  W32.AIDetectMalware.64
MaxSecure:  Trojan.Malware.300983.susgen
Cynet:  Malicious (score: 100)
SecureAge: Malicious

https://www.virustotal.com/gui/file/11006e9229152809738089212accff2fd0822194f70357e51aec60f35d562074

![VirusTotalA](https://github.com/DannyBen/FlicFlac/assets/161966155/8f8fe6a8-67ca-4089-bc15-c0bbf5430b64)

**Comment by DannyBen** [comment]
Nothing I can do about it.

Feel free to compile from source yourself - there is a [compile script in the repository](https://github.com/DannyBen/FlicFlac/blob/master/Compile.ahk).

**Comment by Luc4Piccinini** [comment]
Since you programmed it do you confirm that they are all false positives? 
I don't think I can solve this problem.

**Comment by DannyBen** [comment]
This is an issue with many AutoHotkey tools. If you search "AutoHotkey virus total false positive" you will find many.
[Example](https://www.tenforums.com/software-apps/207392-autohotkey-software-flagged-virustotal.html).

This is open source, you can review the code and if you don't trust the EXE, it is quite easy to compile it yourself - just install v1.1 of AutoiHotkey from the [official site](https://www.autohotkey.com/), download the repository as zip file (or git pull), and run the Compile.ahk code.

To my knowledge and understanding, a) my code (FlicFlac.ahk) is not malicious, and b) the binaries it brings with it (flac.exe, MAC.exe etc) and AutoHotkey itself, are not malicious - but you need to judge for yourself and seek alternatives if you deem the risk too high.
