### ISSUE TITLE
WAV 24bit 48khz to FLAC or APE fail

### ISSUE THREAD

**Issue by fafayqa** [DannyBen/FlicFlac#16]
If I drag'n'drop 24bit 48khs audio file and set to convert it to FLAC or APE, it fails with error: "An error has occured, Failed to convert".
On the other hand converting the same file to MP3 or OGG is without any problem.

**Comment by DannyBen** [comment]
Perhaps it has something to do with the version of the flac / ape converter. If they do not accept it, then there is little I can do about it.

Can you provide a sample file?
