### ISSUE TITLE
m4a Problem

### ISSUE THREAD

**Issue by Phantom995** [DannyBen/FlicFlac#17]
Hello,

Nice App, but 
convertion from m4a don´t work. Can you help?

![Unblk](https://github.com/user-attachments/assets/366fc271-7dd3-40ce-b857-e4a8289e264a)

Thanks,
Dennis

**Comment by DannyBen** [comment]
I need the file that is failing in order to help.

**Comment by Phantom995** [comment]
Thanks for the quick response.

Here is the file, I have to zip it to upload.
[test m4a.zip](https://github.com/user-attachments/files/17775493/test.m4a.zip)

**Comment by DannyBen** [comment]
This m4a container contains a flac encoded file.
FlicFlac uses `faad.exe` to convert m4a files, which is assumed to contain AAC files.

**Comment by Phantom995** [comment]
Ok I understand. 
Thanks anyway for the research.

**Comment by DannyBen** [comment]
Sure. Sorry I couldn't help.
