### ISSUE TITLE
Support for .m4a files

### ISSUE THREAD

**Issue by tooomm** [DannyBen/FlicFlac#4]
I would like to input .m4a files as well to convert them to e.g. mp3.

Have you thought about supporting them?

---

I had to go to your page and "search" there just to find out that the file format is not supported. Maybe include a pop up hint when somebody tries to input any unsupported file format and let them know.

**Comment by DannyBen** [comment]
Not sure why you had to search for supported formats, the list of supported formats appears multiple times in both the [download page](https://sector-seven.com/software/flicflac) and the README in this repository - plus: if there is no "to XXX" button in the UI, it is not supported.

If there is an m4a <-> wav, standalone, lightweight CLI converter for windows, then adding it should not be difficult.  As this is not a format I need, I am unlikely to invest too much time in it - if you find one, post the link here and I might take a deeper look into adding it.

**Comment by tooomm** [comment]
>Not sure why you had to search for supported formats, the list of supported formats appears multiple times in both the download page and the README in this repository

I downloaded the app years ago and just opened it to use it. That's why I had to start searching as the app itself doesn't tell you right away from the interface about that. ;)

>if there is no "to XXX" button in the UI, it is not supported.

That's not intuitive and could just mean (as the label tells you) that this are supported **output** formats to select from.

<br>

If you click and browse for files the supported (input) file formats are also listed...
But again, that's hidden and not straight forward.

Using drag&drop tells you nothing at all. It just doesn't work with a m4a file. The progress bar flickers and that's it. At first I thought I just can't find the output files, the app is broken or I may miss a library etc.
As mentioned, there could be some helpful hint when trying to use an unsupported format.
One can also manually browse for an unsupported file format and select is as input with the same "confusing" result.

The simple UI and drag&drop way of converting is why I love your tool and always keep it around as it's portable. However, I don't have to use it often.
Hope my descriptions help you to improve the tool and make it even easier/more clear to use.

---

>If there is an m4a <-> wav, standalone, lightweight CLI converter for windows, then adding it should not be difficult. As this is not a format I need, I am unlikely to invest too much time in it - if you find one, post the link here and I might take a deeper look into adding it.

Sorry, I can't point you in the right direction right now. :/
If I find something I post it here. Or maybe somebody else does...

m4a container (AAC inside) are commonly used by Apple for example.

**Comment by tooomm** [comment]
>If there is an m4a <-> wav, standalone, lightweight CLI converter for windows, then adding it should not be difficult.

https://superuser.com/questions/23930/how-to-decode-aac-m4a-audio-files-into-wav
mentions e.g. ffmpeg, avconv, faad2

Hope that helps.

**Comment by DannyBen** [comment]
ffmpeg and avconv are heavy, and the only compiled binary I found of faad only does one way conversion (to wav, not back to m4a).

**Comment by tooomm** [comment]
>ffmpeg and avconv are heavy, and the only compiled binary I found of faad only does one way conversion (to wav, not back to m4a)

Hmm. Are they that big that this drawback isn't out-weighted by the additional feature options?
The size of the tool shouldn't matter as much in recent times?

I mean... input support would be sufficient for me. As the output options are nice.
I honestly would just need wav, flac and mp3 (maybe ogg) probably. But the more input, the better!

But that might not be your approach with the tool.

**Comment by DannyBen** [comment]
Yes, they are big.

As hinted by the name, FlicFlac was originally designed to be a one trick pony: Convert between Flac and WAV. Then, the "feature creep" started and more formats were added.

You might find another tool of mine more useful - it is more flexible and you can add your own "jobs" to is (although I think it already supports m4a)

https://sector-seven.com/software/fileblender

Works like this:

![screencast](https://user-images.githubusercontent.com/2405099/79255364-d6a7d300-7e8e-11ea-89b3-14be71845b33.gif)

**Comment by DannyBen** [comment]
BTW - are you looking to convert m4a to other formats, or to convert other formats TO m4a?

**Comment by DannyBen** [comment]
Released version 1.10 with support for m4a and aac (input only)

**Comment by nikhilCad** [comment]
@DannyBen just wanted to say thank you for this wonderful and simple program.

**Comment by DannyBen** [comment]
Sure thing! Glad it is still useful after 12 years.
In fact, looking at the changelog now, its "birthday" is in a few days (released on May 27 2008).

**Comment by tooomm** [comment]
Too late for the 13th birthday, but still wanted to reply. ;)

>BTW - are you looking to convert m4a to other formats, or to convert other formats TO m4a?

I was looking for import support (converting m4a to other formats). Thanks for taking the time and looking into this request! I really like the way the tool handles things and it's simplicity.

I mostly forgot about this issue but ran into the same problem the other day and recalled this.

All Apple devices do sound recordings to .m4a audio container nowadays. The need to convert them for compatibility reasons was the root of this request. (no more wav recordings 😢)
When trying to convert them it always gives me an error in flicflac 1.10. Other file types do work and when throwing the same .m4a files at your "multi tool" fileblender... they are processed without issues!

Do you have any clue what might cause this limitation in flicflac?

**Comment by DannyBen** [comment]
> Do you have any clue what might cause this limitation in flicflac?

Well. FlicFlac is using faad.exe, and File Blender is using the heavier ffmpeg. This could be a reason for the difference.

Now, faad.exe should work just fine.

FlicFlac is currently shipped with faad 2.7, and I see that [version 2.10](https://www.rarewares.org/aac-decoders.php) is available.

So - two options:

1. Download faad.exe from that link, and test it manually (in the command line) with your file.
2. Send me a sample file that fails, and I can try (you can send by email if its sensitive).

If this works with the newer faad, I will release a new version with it included.

**Comment by tooomm** [comment]
I just send two test files to you that do not work with flicflac. Check your mail @DannyBen.

It looks like fileblender behaves unexpected as well... I can extract an mp3 from those files, but not convert to mp3. Wondering what the difference of those options is in the first place. 🤔

**Comment by DannyBen** [comment]
Well - as you mentioned, these are ALAC files, not AAC. Not supported by FlicFlac, and probably not by File Blender.

**Comment by tooomm** [comment]
>Well - as you mentioned, these are ALAC files, not AAC

Those are the details from both files:
![samplea](https://user-images.githubusercontent.com/9874850/131268158-5f03a651-038a-40ad-af59-ddf20c42e8b0.png)
![sampleb](https://user-images.githubusercontent.com/9874850/131268159-ef6796ac-19b1-495a-b428-54cf293263c9.png)

The first is not AAC, even though labelled as such?

**Comment by DannyBen** [comment]
Perhaps it is...

The faad error is just "invalid atom size 1 @20"
