### ISSUE TITLE
Preserve meta information when converting

### ISSUE THREAD

**Issue by Arutosio** [DannyBen/FlicFlac#6]
can we implement on mp3 convert to save new file with all informate that is include on flac for exsample title, description, Artist, album, date, ecc..

**Comment by DannyBen** [comment]
Unlikely. FlicFlac uses external EXE files for the conversion. Reading/writing the metadata for each of the supported formats is beyond the scope of what I needed FlicFlac to do and is much more complex - especially since some formats are going through 2 conversion steps.

**Comment by Arutosio** [comment]
sad 😭

**Comment by DannyBen** [comment]
If you are a AutoHotkey developer, and wish to try implementing it together, I have no objection.

**Comment by Arutosio** [comment]
No I'm not

**Comment by DannyBen** [comment]
Ok - let's leave the issue open for now, maybe I will try to implement something sometime.
