### ISSUE TITLE
Shell integration - multiple audio files

### ISSUE THREAD

**Issue by brunetton** [DannyBen/FlicFlac#8]
Hi

I just discovered FlicFlac and I really find it super usefull ! Simple and efficient. I was looking for such a software to help friends that send me audio files but don't know how to convert to flac before sending them.

But we often send a LOT of files; and we miss shell integration for multiple files.

Do you plan to add it ? Do you think it's a lot of work to add this ? (I can try, but I didn't worked in windows environment for years)

Thanks a lot

**Comment by DannyBen** [comment]
Shouldn't be difficult I think, but up until now, I did not have plans of adding it.

Isn't dragging multiple files onto the GUI just as efficient?

**Comment by brunetton** [comment]
Thank you for your answer. I don't think this is as efficient because for drag'n drop files to the app user will have to:
- lunch the app
- resize file browser to make both apps visible
- select files and drag them into the app

Using shell integration:
- select files, right click

**Comment by jamesBrosnahan** [comment]
Can something like bash wildcard expansion be added to the open file screen to get all files of the same format from a folder structure? [I have m4a music from Itunes I want to make copies of as wavs or flacs for testing Demucs and RVC software b/c the Demucs software I have doesn't support m4a]

**Comment by DannyBen** [comment]
How is bash relevant to a Windows software?

The open file dialog is a standard Windows dialog, and you can select multiple files there with Shift / Ctrl. Doesn't this work for you?

**Comment by DannyBen** [comment]
But - now that you have bumped this issue back to my attention - I will take another try at it.
I believe I identified the path to the solution.

**Comment by jamesBrosnahan** [comment]
I want to select all files of a certain type (m4a) starting from a top folder. Selecting all the folders just opens one of the folder in the file select dialog without opening any songs.

music
  -> artists
       --> album1
            ---> songs
       --> album2
            ---> songs
        --> album3
             ---> songs

I want to be able to open all the songs in every folder from the top level and convert everything.

Bash has wildcard expansions, but CMD doesn't; wildcard expansions can be used to open all files nested at the same level by type with something like './\*/\*/\*.m4a'

**Comment by DannyBen** [comment]
I just remembered that the problem is that when selecting multiple files in the context menu, it opens that many FlicFlac instances, and sends one file to each.

I don't see a way to implement multiple files in the context menu.
If someone wants to try to implement it, I might accept a PR.
